<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hode</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <nav>
        <div class="container">
            <div class="row">
                <div class="col-md-2 logo">
                    <img src="assets/images/logo-menu.svg" alt="">
                </div>
                <div class="col-md-10 menu">
                    <ul>
                        <li><a href="#home">Home</a></li>
                        <li><a href="#fazemos">Soluções</a></li>
                        <li><a href="">Experiências</a></li>
                        <li><a href="" class="btn-hode">Contate-nos</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div id="hero">
        <div class="container">
            <h1>Atrair <b>Mais Clientes</b></h1>
            <h1>Por Meio <b>Digital</b></h1>
            <div class="btn-hero">
                <a href="" class="btn-hode">Contate-nos</a>
                <a href="" class="btn-hode-borda">Serviços</a>
            </div>
            <img src="assets/images/img-hero.svg" alt="">
        </div>
    </div>

    <div id="fazemos">
        <div class="container">
            <h2>o que nós fazemos</h2>
            <div class="servicos">
                <div class="servicos-item">
                    <div class="item-img">
                        <img src="assets/images/fazemos03.svg" alt="">
                    </div>
                    <div class="item-text">
                        <h3><b>sites</b></h3>
                        <p>É a identidade online da sua empresa. Aliamos tecnologia e design para apresentar sua empresa ou o seu serviço na web.</p>
                    </div>
                </div>
                <div class="servicos-item">
                    <div class="item-img">
                        <img src="assets/images/fazemos01.svg" alt="">
                    </div>
                    <div class="item-text">
                        <h3><b>hospedagem</b></h3>
                        <p>Sistema de hospedagem para Web site e e-mails. Segurança e sigilo para suas informações.</p>
                    </div>
                </div>
                <div class="servicos-item">
                    <div class="item-img">
                        <img src="assets/images/fazemos02.svg" alt="">
                    </div>
                    <div class="item-text">
                        <h3><b>otimização de busca - SEO</b></h3>
                        <p>Melhoria em posicionamento e tráfego. Sua empresa entre as mais vistas nos sites de busca.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>